name: Build and test
on:
  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run unit tests
        run: bundle exec fastlane unit_tests
        
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
